package ImpactoExpress;

import static ImpactoExpress.tela.clientes;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joao
 * @version 1.0
 * @since 8nov2016
 * 
 */
public class telaRelatorioClientes extends javax.swing.JInternalFrame {
    DefaultTableModel modelo;
    PegaFuncionarios getListaFuncionarios = new PegaFuncionarios();
    PegaClientes getListaClientes = new PegaClientes();
    PegaVeiculos getListaVeiculos = new PegaVeiculos();
    ExportCliente exportaC= new ExportCliente();
    /**
     * Creates new form telaRelatorioClientes
     */
    public telaRelatorioClientes() {
        initComponents();
        getListaFuncionarios.getListaFuncionarios();
        getListaClientes.getListaClientes();
        getListaVeiculos.getListaVeiculos();
        modelo = (DefaultTableModel) jTable1.getModel();
        gerarRelatorioClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnExportaCliente = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Relatorio Clientes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Email", "Telefone 1", "Telefone 2", "Cidade", "Endereco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnExportaCliente.setText("Exporta");
        btnExportaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExportaCliente))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExportaCliente)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportaClienteActionPerformed
        exportaC.ExportarCliente(clientes.get(jTable1.getSelectedRow()));
    }//GEN-LAST:event_btnExportaClienteActionPerformed
    public void gerarRelatorioClientes(){
        modelo.setNumRows(0);
        if(clientes.isEmpty()){
            String[] linha= {"---","---","---","---","---","---","---"};
            modelo.addRow(linha);
        }
        else
            for(Cliente c: clientes){
                String[] linha= {c.getIdCliente()+"", c.getNomeCliente(),
                    c.getEmailCliente(), c.getTelefone1Cliente(),
                    c.getTelefone2Cliente(), c.getCidadeCliente(),
                    c.getEnderecoCliente()};
                modelo.addRow(linha);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportaCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
